/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../node_modules/.cache/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  link?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?:
    | "Technical Partners"
    | "Industry Partners"
    | "Research Partners"
    | "Venture Capital"
    | "Initiatives";
  tier?: "gold" | "silver" | "bronze" | "supporter";
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  desc?: string;
  event_date: string;
  end_date?: string;
  location?: string;
  city?: "Munich" | "Online";
  category?: "Hackathon" | "Speaker" | "Event" | "E-Lab";
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sign_up?: string;
  detail?: string;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  desc?: string;
  status?: "ongoing" | "completed";
  publication?: string;
  keywords?: Array<string>;
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | Research
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../lib/sanity-queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"]{  "id": _id,  title,  "description": coalesce(desc, ""),  event_date,  location,  city,  category,  "poster": poster.asset->url,  "images": array::compact([poster.asset->url, img.asset->url]),  sign_up}
export type EVENTS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  event_date: string;
  location: string | null;
  city: "Munich" | "Online" | null;
  category: "E-Lab" | "Event" | "Hackathon" | "Speaker" | null;
  poster: string | null;
  images: Array<string>;
  sign_up: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: RESEARCH_QUERY
// Query: *[_type == "research"]{  "id": _id,  title,  "description": coalesce(desc, ""),  status,  publication,  "keywords": coalesce(keywords, []),  "image": img.asset->url}
export type RESEARCH_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  status: "completed" | "ongoing" | null;
  publication: string | null;
  keywords: Array<string> | Array<never>;
  image: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category:
    | "Industry Partners"
    | "Initiatives"
    | "Research Partners"
    | "Technical Partners"
    | "Venture Capital"
    | null;
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: RESEARCH_PARTNERS_QUERY
// Query: *[_type == "partner" && category == "Research Partners"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type RESEARCH_PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category: "Research Partners";
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_EVENTS_QUERY
// Query: *[_type == "event"]{  "id": _id,  title,  "description": coalesce(desc, ""),  event_date,  location,  city,  category,  "poster": poster.asset->url,  "images": array::compact([poster.asset->url, img.asset->url]),  sign_up,  detail}
export type PUBLIC_EVENTS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  event_date: string;
  location: string | null;
  city: "Munich" | "Online" | null;
  category: "E-Lab" | "Event" | "Hackathon" | "Speaker" | null;
  poster: string | null;
  images: Array<string>;
  sign_up: string | null;
  detail: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_RESEARCH_QUERY
// Query: *[_type == "research"]{  "id": _id,  title,  "description": coalesce(desc, ""),  status,  publication,  "keywords": array::join(keywords, ", "),  "image": img.asset->url}
export type PUBLIC_RESEARCH_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  status: "completed" | "ongoing" | null;
  publication: string | null;
  keywords: string | null;
  image: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_PARTNERS_QUERY
// Query: *[_type == "partner"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type PUBLIC_PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category:
    | "Industry Partners"
    | "Initiatives"
    | "Research Partners"
    | "Technical Partners"
    | "Venture Capital"
    | null;
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;
