/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../node_modules/.cache/sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  link?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?:
    | "Technical Partners"
    | "Industry Partners"
    | "Research Partners"
    | "Venture Capital"
    | "Initiatives";
  tier?: "gold" | "silver" | "bronze" | "supporter";
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  desc?: string;
  event_date: string;
  end_date?: string;
  location?: string;
  city?: "Munich" | "Online";
  category?: "Hackathon" | "Speaker" | "Event" | "E-Lab";
  hosts?: Array<string>;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sign_up?: string;
  detail?: string;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  desc?: string;
  status?: "ongoing" | "completed";
  publication?: string;
  keywords?: Array<string>;
  img?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TaskForce = {
  _id: string;
  _type: "taskForce";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  name: string;
  slug: Slug;
  field: string;
  description: string;
  detailedDescription: string;
  work?: {
    partner: string;
    items: Array<string>;
  };
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoCaption?: string;
};

export type ProjectsCopy = {
  _id: string;
  _type: "projectsCopy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    title: string;
    lead: string;
    figureLabel: string;
  };
  openSeat?: {
    name: string;
    field: string;
  };
  closing?: {
    title: string;
    lead: string;
    student?: {
      audience: string;
      text: string;
    };
    partner?: {
      audience: string;
      text: string;
      textWithoutPartner: string;
    };
  };
};

export type Department = {
  _id: string;
  _type: "department";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  name: string;
  description: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  photoCaption?: string;
};

export type JourneyStep = {
  _id: string;
  _type: "journeyStep";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order: number;
  stage: number;
  number: string;
  name: string;
  description: string;
  iconKey:
    | "rocket"
    | "brain"
    | "handshake"
    | "chart"
    | "globe"
    | "graduation-cap";
  fromSemester: number;
  span: "event" | "ongoing";
  evidence?: {
    name: string;
    excerpt: string;
  };
};

export type CommunityCopy = {
  _id: string;
  _type: "communityCopy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    title: string;
    lead: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    photoCaption: string;
  };
  journey?: {
    title: string;
    lead: string;
  };
  departments?: {
    title: string;
    lead: string;
  };
  closing?: {
    title: string;
    lead: string;
    companiesReader: string;
  };
};

export type QandaCopy = {
  _id: string;
  _type: "qandaCopy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle: string;
  missionQuestion: string;
  missionLead: string;
  missionPassage: string;
  closing?: {
    title: string;
    lead: string;
    action: string;
  };
  forks?: {
    students?: {
      reader: string;
      text: string;
    };
    companies?: {
      reader: string;
    };
  };
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  collection: "apply" | "e-lab" | "qanda";
  order: number;
  question: string;
  answer: string;
  anchor?: string;
  points?: Array<string>;
  spans?: Array<string>;
  evidence?: {
    text?: string;
    label?: string;
    href?: string;
  };
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | Research
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug
  | TaskForce
  | ProjectsCopy
  | Department
  | JourneyStep
  | CommunityCopy
  | QandaCopy
  | Faq;

// Source: ../features/community/content.ts
// Variable: COMMUNITY_COPY_QUERY
// Query: *[_id == "communityCopy"][0]{  hero{ title, lead, "photo": photo{  "src": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  alt,  "hotspot": hotspot{ x, y }}, photoCaption },  journey{ title, lead },  departments{ title, lead },  closing{ title, lead, companiesReader }}
export type COMMUNITY_COPY_QUERY_RESULT =
  | {
      hero: null;
      journey: null;
      departments: null;
      closing: null;
    }
  | {
      hero: null;
      journey: null;
      departments: null;
      closing: {
        title: string;
        lead: string;
        companiesReader: null;
      } | null;
    }
  | {
      hero: {
        title: string;
        lead: string;
        photo: null;
        photoCaption: null;
      } | null;
      journey: null;
      departments: null;
      closing: {
        title: string;
        lead: string;
        companiesReader: null;
      } | null;
    }
  | {
      hero: {
        title: string;
        lead: string;
        photo: {
          src: string | null;
          width: number | null;
          height: number | null;
          alt: string | null;
          hotspot: {
            x: number;
            y: number;
          } | null;
        };
        photoCaption: string;
      } | null;
      journey: {
        title: string;
        lead: string;
      } | null;
      departments: {
        title: string;
        lead: string;
      } | null;
      closing: {
        title: string;
        lead: string;
        companiesReader: string;
      } | null;
    }
  | null;

// Source: ../features/projects/content.ts
// Variable: PROJECTS_CONTENT_QUERY
// Query: {  "copy": *[_id == "projectsCopy"][0]{    hero{ eyebrow, title, lead, figureLabel },    openSeat{ name, field },    closing{      title,      lead,      student{ audience, text },      partner{ audience, text, textWithoutPartner }    }  },  "taskForces": *[_type == "taskForce"] | order(order asc){    "slug": slug.current,    name,    field,    description,    detailedDescription,    work{ partner, items },    "photo": photo{  "src": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  alt,  "hotspot": hotspot{ x, y }},    photoCaption  }}
export type PROJECTS_CONTENT_QUERY_RESULT = {
  copy:
    | {
        hero: null;
        openSeat: null;
        closing: null;
      }
    | {
        hero: null;
        openSeat: null;
        closing: {
          title: string;
          lead: string;
          student: null;
          partner: null;
        } | null;
      }
    | {
        hero: {
          eyebrow: null;
          title: string;
          lead: string;
          figureLabel: null;
        } | null;
        openSeat: null;
        closing: {
          title: string;
          lead: string;
          student: null;
          partner: null;
        } | null;
      }
    | {
        hero: {
          eyebrow: string;
          title: string;
          lead: string;
          figureLabel: string;
        } | null;
        openSeat: {
          name: string;
          field: string;
        } | null;
        closing: {
          title: string;
          lead: string;
          student: {
            audience: string;
            text: string;
          } | null;
          partner: {
            audience: string;
            text: string;
            textWithoutPartner: string;
          } | null;
        } | null;
      }
    | null;
  taskForces: Array<{
    slug: string;
    name: string;
    field: string;
    description: string;
    detailedDescription: string;
    work: {
      partner: string;
      items: Array<string>;
    } | null;
    photo: {
      src: string | null;
      width: number | null;
      height: number | null;
      alt: string | null;
      hotspot: {
        x: number;
        y: number;
      } | null;
    } | null;
    photoCaption: string | null;
  }>;
};

// Source: ../features/qanda/content.ts
// Variable: QANDA_CONTENT_QUERY
// Query: {  "copy": *[_id == "qandaCopy"][0]{    heroTitle,    missionQuestion,    missionLead,    missionPassage,    closing{ title, lead, action },    forks{ students{ reader, text }, companies{ reader } }  },  "faqs": *[_type == "faq" && collection == "qanda"] | order(order asc){    "id": anchor,    question,    answer,    points,    spans,    evidence{ text, label, href }  }}
export type QANDA_CONTENT_QUERY_RESULT = {
  copy:
    | {
        heroTitle: null;
        missionQuestion: null;
        missionLead: null;
        missionPassage: null;
        closing: null;
        forks: null;
      }
    | {
        heroTitle: null;
        missionQuestion: null;
        missionLead: null;
        missionPassage: null;
        closing: {
          title: string;
          lead: string;
          action: null;
        } | null;
        forks: null;
      }
    | {
        heroTitle: string;
        missionQuestion: string;
        missionLead: string;
        missionPassage: string;
        closing: {
          title: string;
          lead: string;
          action: string;
        } | null;
        forks: {
          students: {
            reader: string;
            text: string;
          } | null;
          companies: {
            reader: string;
          } | null;
        } | null;
      }
    | null;
  faqs: Array<{
    id: string | null;
    question: string;
    answer: string;
    points: Array<string> | null;
    spans: Array<string> | null;
    evidence: {
      text: string | null;
      label: string | null;
      href: string | null;
    } | null;
  }>;
};

// Source: ../lib/community-content.ts
// Variable: JOURNEY_QUERY
// Query: *[_type == "journeyStep"] | order(order asc){  "step": number,  name,  description,  iconKey,  fromSemester,  span,  stage,  evidence{ name, excerpt }}
export type JOURNEY_QUERY_RESULT = Array<{
  step: string;
  name: string;
  description: string;
  iconKey:
    | "brain"
    | "chart"
    | "globe"
    | "graduation-cap"
    | "handshake"
    | "rocket";
  fromSemester: number;
  span: "event" | "ongoing";
  stage: number;
  evidence: {
    name: string;
    excerpt: string;
  } | null;
}>;

// Source: ../lib/community-content.ts
// Variable: DEPARTMENTS_QUERY
// Query: *[_type == "department"] | order(order asc){  name,  description,  "photo": photo{  "src": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  alt,  "hotspot": hotspot{ x, y }},  photoCaption}
export type DEPARTMENTS_QUERY_RESULT = Array<{
  name: string;
  description: string;
  photo: {
    src: string | null;
    width: number | null;
    height: number | null;
    alt: string | null;
    hotspot: {
      x: number;
      y: number;
    } | null;
  } | null;
  photoCaption: string | null;
}>;

// Source: ../lib/faq-content.ts
// Variable: FAQ_QUERY
// Query: *[_type == "faq" && collection == $collection] | order(order asc){  question,  answer}
export type FAQ_QUERY_RESULT = Array<{
  question: string;
  answer: string;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"]{  "id": _id,  title,  "description": coalesce(desc, ""),  event_date,  location,  city,  category,  "hosts": coalesce(hosts, []),  "poster": poster.asset->url,  "images": array::compact([poster.asset->url, img.asset->url]),  sign_up}
export type EVENTS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  event_date: string;
  location: string | null;
  city: "Munich" | "Online" | null;
  category: "E-Lab" | "Event" | "Hackathon" | "Speaker" | null;
  hosts: Array<string> | Array<never>;
  poster: string | null;
  images: Array<string>;
  sign_up: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: RESEARCH_QUERY
// Query: *[_type == "research"]{  "id": _id,  title,  "description": coalesce(desc, ""),  status,  publication,  "keywords": coalesce(keywords, []),  "image": img.asset->url}
export type RESEARCH_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  status: "completed" | "ongoing" | null;
  publication: string | null;
  keywords: Array<string> | Array<never>;
  image: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category:
    | "Industry Partners"
    | "Initiatives"
    | "Research Partners"
    | "Technical Partners"
    | "Venture Capital"
    | null;
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: RESEARCH_PARTNERS_QUERY
// Query: *[_type == "partner" && category == "Research Partners"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type RESEARCH_PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category: "Research Partners";
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_EVENTS_QUERY
// Query: *[_type == "event"]{  "id": _id,  title,  "description": coalesce(desc, ""),  event_date,  location,  city,  category,  "poster": poster.asset->url,  "images": array::compact([poster.asset->url, img.asset->url]),  sign_up,  detail}
export type PUBLIC_EVENTS_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  event_date: string;
  location: string | null;
  city: "Munich" | "Online" | null;
  category: "E-Lab" | "Event" | "Hackathon" | "Speaker" | null;
  poster: string | null;
  images: Array<string>;
  sign_up: string | null;
  detail: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_RESEARCH_QUERY
// Query: *[_type == "research"]{  "id": _id,  title,  "description": coalesce(desc, ""),  status,  publication,  "keywords": array::join(keywords, ", "),  "image": img.asset->url}
export type PUBLIC_RESEARCH_QUERY_RESULT = Array<{
  id: string;
  title: string;
  description: string | "";
  status: "completed" | "ongoing" | null;
  publication: string | null;
  keywords: string | null;
  image: string | null;
}>;

// Source: ../lib/sanity-queries.ts
// Variable: PUBLIC_PARTNERS_QUERY
// Query: *[_type == "partner"]{  "id": _id,  name,  link,  "image": image.asset->url,  category,  tier,  featured}
export type PUBLIC_PARTNERS_QUERY_RESULT = Array<{
  id: string;
  name: string;
  link: string | null;
  image: string | null;
  category:
    | "Industry Partners"
    | "Initiatives"
    | "Research Partners"
    | "Technical Partners"
    | "Venture Capital"
    | null;
  tier: "bronze" | "gold" | "silver" | "supporter" | null;
  featured: boolean | null;
}>;
