/**
 * CMS record types, derived from the Sanity TypeGen output
 * (`sanity.types.generated.ts`, regenerated by `pnpm sanity:typegen`).
 *
 * Page types are the query results with `null` fields made optional: the
 * fetch layer in `lib/sanity.ts` drops the `null`s GROQ returns for missing
 * fields (see `omitNulls`). Enum fields keep the unions from the schema
 * `options.list`, so a new category or status is a schema edit plus a
 * regenerate, and TypeScript points at every place that has to handle it.
 */
import type { WithoutNulls } from "./omit-nulls";
import type {
  EVENTS_QUERY_RESULT,
  PARTNERS_QUERY_RESULT,
  PUBLIC_EVENTS_QUERY_RESULT,
  PUBLIC_PARTNERS_QUERY_RESULT,
  PUBLIC_RESEARCH_QUERY_RESULT,
  RESEARCH_QUERY_RESULT,
} from "./sanity.types.generated";

/** An event on /events. */
export type Event = WithoutNulls<EVENTS_QUERY_RESULT[number]>;
/** "E-Lab" | "Event" | "Hackathon" | "Speaker". */
export type EventCategory = NonNullable<Event["category"]>;
/** "Munich" | "Online". */
export type EventCity = NonNullable<Event["city"]>;

/** A partner on /partners, /research and the homepage. */
export type Partner = WithoutNulls<PARTNERS_QUERY_RESULT[number]>;
/** "gold" | "silver" | "bronze" | "supporter". */
export type PartnerTier = NonNullable<Partner["tier"]>;

/** A research project on /research; `keywords` is always an array. */
export type ResearchProject = WithoutNulls<RESEARCH_QUERY_RESULT[number]>;
/** "ongoing" | "completed". */
export type ResearchStatus = NonNullable<ResearchProject["status"]>;

/**
 * @deprecated Compatibility shape for the research page until its card takes
 * `ResearchProject` (keywords as an array): `keywords` is the list joined
 * with ", ", as the query returned it before. Produced by `joinKeywords` in
 * the /research route; remove both once the card reads the array.
 */
export type Research = Omit<ResearchProject, "keywords"> & {
  keywords?: string;
};

/** `/api/getNotes` item. Public contract: do not change the shape. */
export type PublicEvent = PUBLIC_EVENTS_QUERY_RESULT[number];
/** `/api/getPartners` item. Public contract: do not change the shape. */
export type PublicPartner = PUBLIC_PARTNERS_QUERY_RESULT[number];
/** `/api/getResearch` item. Public contract: do not change the shape. */
export type PublicResearch = PUBLIC_RESEARCH_QUERY_RESULT[number];
