/**
 * CMS record types, derived from the Sanity TypeGen output
 * (`sanity.types.generated.ts`, regenerated by `pnpm sanity:typegen`).
 *
 * Page types are the query results with `null` fields made optional (except
 * `Partner`, a partner organisation as the partners feature maps it): the
 * fetch layer in `lib/sanity.ts` drops the `null`s GROQ returns for missing
 * fields (see `omitNulls`). Enum fields keep the unions from the schema
 * `options.list`, so a new category or status is a schema edit plus a
 * regenerate, and TypeScript points at every place that has to handle it.
 */
import type { WithoutNulls } from "./omit-nulls";
import type { PartnerCategory, PartnerTier } from "./people-and-logos";
import type {
  EVENTS_QUERY_RESULT,
  PUBLIC_EVENTS_QUERY_RESULT,
  PUBLIC_PARTNERS_QUERY_RESULT,
  PUBLIC_RESEARCH_QUERY_RESULT,
  RESEARCH_QUERY_RESULT,
} from "./sanity.types.generated";

/** An event on /events. */
export type Event = WithoutNulls<EVENTS_QUERY_RESULT[number]>;
/** "E-Lab" | "Event" | "Hackathon" | "Speaker". */
export type EventCategory = NonNullable<Event["category"]>;

/**
 * A partner on /partners, /research and the homepage: a partner
 * organisation (`organization` with a partnership) as the pages list it.
 */
export type Partner = {
  /** The organisation's key. */
  id: string;
  name: string;
  /** Its website. */
  link?: string;
  /** Its logo for light backgrounds. */
  image?: string;
  category?: PartnerCategory;
  /** Missing counts as "supporter". */
  tier?: PartnerTier;
  /** Leads its tier. */
  featured?: boolean;
  /** Optional CMS editorial order within its tier. */
  order?: number;
  /** The logo is a symbol without the name: pages set the name beside it. */
  symbolOnly?: true;
};

/** A research project on /research; `keywords` is always an array. */
export type ResearchProject = WithoutNulls<RESEARCH_QUERY_RESULT[number]>;
/** "ongoing" | "completed". */
export type ResearchStatus = NonNullable<ResearchProject["status"]>;

/** `/api/getNotes` item. Public contract: do not change the shape. */
export type PublicEvent = PUBLIC_EVENTS_QUERY_RESULT[number];
/** `/api/getPartners` item. Public contract: do not change the shape. */
export type PublicPartner = PUBLIC_PARTNERS_QUERY_RESULT[number];
/** `/api/getResearch` item. Public contract: do not change the shape. */
export type PublicResearch = PUBLIC_RESEARCH_QUERY_RESULT[number];
