import { defineConfig, devices, type Project } from "@playwright/test";

/**
 * End-to-end, accessibility and visual tests (`pnpm test:e2e`). Specs live in
 * `e2e/`; unit and component tests run in Vitest (`vitest.config.ts`).
 *
 * The suite runs against a production build served with the mock CMS
 * (`USE_MOCK_CMS=1`), so no Sanity credentials are needed. Locally an already
 * running server on `PORT` is reused: start one with
 * `USE_MOCK_CMS=1 pnpm build && USE_MOCK_CMS=1 pnpm start`, or let Playwright
 * build and start it. Set `PORT` to keep clear of another server on 3000.
 *
 * Projects (each spec opts into the ones where it makes sense, by file):
 *
 * | project          | browser  | viewport        | specs                                |
 * | ---------------- | -------- | --------------- | ------------------------------------ |
 * | chromium-desktop | chromium | 1440×900        | routes, a11y, keyboard, partners, routing |
 * | chromium-laptop  | chromium | 1024×768        | layout, mobile menu                  |
 * | chromium-tablet  | chromium | 768×1024        | layout, mobile menu                  |
 * | chromium-small   | chromium | 320×640         | routes                               |
 * | webkit-desktop   | webkit   | 1440×900        | layout, keyboard                     |
 * | webkit-iphone    | webkit   | iPhone 15       | routes, a11y, mobile menu, partners  |
 * | reduced-motion   | chromium | 1440×900        | motion                               |
 * | no-js            | chromium | 1440×900        | no-js                                |
 *
 * Visual regression (`visual.spec.ts`) runs only with `pnpm test:e2e:visual`
 * (`E2E_VISUAL=1`), in the `visual-chromium` and `visual-webkit` projects.
 * Baselines are Linux screenshots from the official Playwright Docker image,
 * generated by `.github/workflows/e2e-snapshots.yml`.
 */

const isCI = Boolean(process.env.CI);
const isVisualRun = process.env.E2E_VISUAL === "1";
const port = Number(process.env.PORT ?? 3000);
const baseURL = `http://localhost:${port}`;

/**
 * "Now" for the mock CMS fixtures; keep in sync with `MOCK_CMS_NOW` in
 * e2e/fixtures.ts. The mock clock arrives with W1-Data; until then the server
 * ignores it and no spec depends on dates relative to it.
 */
const mockCmsNow = "2026-10-01T12:00:00Z";

const desktop = { width: 1440, height: 900 };

/** Specs per project. `layout` is the overflow check in routes.spec.ts. */
const functionalProjects: Project[] = [
  {
    name: "chromium-desktop",
    use: { ...devices["Desktop Chrome"], viewport: desktop },
    testMatch: [
      "routes.spec.ts",
      "a11y.spec.ts",
      "keyboard.spec.ts",
      "partners.spec.ts",
      "routing.spec.ts",
    ],
    grepInvert: /@mobile-menu|@layout/,
  },
  {
    name: "chromium-laptop",
    use: {
      ...devices["Desktop Chrome"],
      viewport: { width: 1024, height: 768 },
    },
    testMatch: ["routes.spec.ts", "keyboard.spec.ts"],
    grep: /@layout|@mobile-menu/,
  },
  {
    name: "chromium-tablet",
    use: {
      ...devices["Desktop Chrome"],
      viewport: { width: 768, height: 1024 },
    },
    testMatch: ["routes.spec.ts", "keyboard.spec.ts"],
    grep: /@layout|@mobile-menu/,
  },
  {
    name: "chromium-small",
    use: {
      ...devices["Desktop Chrome"],
      viewport: { width: 320, height: 640 },
    },
    testMatch: ["routes.spec.ts"],
    grepInvert: /@layout/,
  },
  {
    name: "webkit-desktop",
    use: { ...devices["Desktop Safari"], viewport: desktop },
    testMatch: ["routes.spec.ts", "keyboard.spec.ts"],
    grep: /@layout|@keyboard/,
  },
  {
    name: "webkit-iphone",
    // iPhone viewport, user agent, touch and mobile layout, painted at 1x:
    // software rendering at the real 3x starves WebKit's frames on CI runners
    // (timeouts, "element is not stable"). Pixel density is irrelevant to the
    // functional specs; the visual projects cover rendering.
    use: { ...devices["iPhone 15"], deviceScaleFactor: 1 },
    testMatch: [
      "routes.spec.ts",
      "a11y.spec.ts",
      "keyboard.spec.ts",
      "partners.spec.ts",
    ],
    grepInvert: /@layout|@keyboard|@desktop-only/,
  },
  {
    name: "reduced-motion",
    use: {
      ...devices["Desktop Chrome"],
      viewport: desktop,
      reducedMotion: "reduce",
    },
    testMatch: ["motion.spec.ts"],
  },
  {
    name: "no-js",
    use: {
      ...devices["Desktop Chrome"],
      viewport: desktop,
      javaScriptEnabled: false,
    },
    testMatch: ["no-js.spec.ts"],
  },
];

/** Full-page screenshots at 390 and 1440 (set per describe in visual.spec.ts). */
const visualProjects: Project[] = [
  {
    name: "visual-chromium",
    use: { ...devices["Desktop Chrome"], reducedMotion: "reduce" },
    testMatch: ["visual.spec.ts"],
  },
  {
    name: "visual-webkit",
    use: { ...devices["Desktop Safari"], reducedMotion: "reduce" },
    testMatch: ["visual.spec.ts"],
  },
];

export default defineConfig({
  testDir: "e2e",
  fullyParallel: true,
  forbidOnly: isCI,
  retries: isCI ? 2 : 0,
  workers: isCI ? 3 : undefined,
  timeout: 60_000,
  expect: {
    timeout: 10_000,
    toHaveScreenshot: {
      animations: "disabled",
      caret: "hide",
      scale: "css",
      maxDiffPixelRatio: 0.001,
    },
  },
  reporter: [["list"], ["html", { open: "never" }]],
  // Linux baselines are committed; other platforms are local-only (e2e/.gitignore).
  snapshotPathTemplate:
    "{testDir}/__screenshots__/{platform}/{projectName}/{arg}{ext}",
  updateSnapshots: isCI ? "none" : "missing",
  use: {
    baseURL,
    // Visitors are in Munich; the server may run in UTC (CI).
    locale: "en-US",
    timezoneId: "Europe/Berlin",
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: isVisualRun ? visualProjects : functionalProjects,
  webServer: {
    command: "pnpm build && pnpm start",
    url: baseURL,
    reuseExistingServer: !isCI,
    // A cold production build takes a few minutes.
    timeout: 10 * 60_000,
    stdout: "ignore",
    stderr: "pipe",
    env: {
      USE_MOCK_CMS: "1",
      MOCK_CMS_NOW: mockCmsNow,
      NEXT_TELEMETRY_DISABLED: "1",
      PORT: String(port),
    },
  },
});
